app/blueprints/segmentation/forms/segmentation_parameters_form.py
from wtforms import SelectField, RadioField, SubmitField
from wtforms.validators import InputRequired
from flask_wtf import FlaskForm


class SegmentationParametersForm(FlaskForm):

    # Metric based on which to perform segmentation
    metric = SelectField(
        "On what basis do you want to group your customers?",
        choices=[
            ("Total Visits", "Total Visits"),
            ("Total Sales", "Total Sales"),
            ("Total Quantity", "Total Quantity"),
            ("Average Weekly Visits", "Average Weekly Visits"),
            ("Average Weekly Sales", "Average Weekly Sales"),
            ("Average Weekly Quantity", "Average Weekly Quantity"),
            ("Average Monthly Visits", "Average Monthly Visits"),
            ("Average Monthly Sales", "Average Monthly Sales"),
            ("Average Monthly Quantity", "Average Monthly Quantity"),
            ("Average Quarterly Visits", "Average Quarterly Visits"),
            ("Average Quarterly Sales", "Average Quarterly Sales"),
            ("Average Quarterly Quantity", "Average Quarterly Quantity"),
        ],
        validators=[InputRequired()],
    )

    # Options for selecting number of groups
    number_choice = RadioField(
        "How many groups do you want to form?",
        choices=[
            ("auto", "Auto"),
            (2, "2"),
            (3, "3"),
            (4, "4"),
            (5, "5"),
            (6, "6"),
            (7, "7"),
            (8, "8"),
            (9, "9"),
            (10, "10"),
        ],
        default="auto",
        validators=[InputRequired()],
    )

    # Submit button
    submit = SubmitField("OK")

app/blueprints/segmentation/__init__.py
from flask import Blueprint

segmentation_bp = Blueprint(
    "segm",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/segmentation",
)

app/blueprints/segmentation/routes.py
from flask import jsonify, redirect, render_template, request, url_for, flash, session
from flask_login import login_required
from werkzeug.exceptions import RequestEntityTooLarge

from app.forms.file_upload_form import FileUploadForm

from app.services.datasetfile_services import DatasetFileService
from app.services.segmentation.segmentation_services import SegmentationService

from app.blueprints.segmentation import segmentation_bp
from app.blueprints.segmentation.forms.segmentation_parameters_form import (
    SegmentationParametersForm,
)


@segmentation_bp.route("/", methods=["GET"])
@login_required
def segmentation_dashboard():
    """Presents the segmentation page with the file-uploading form."""

    # File-uploading form
    file_upload_form = FileUploadForm()

    # Form to input number of clusters and clustering metric
    segmentation_parameters_form = SegmentationParametersForm()

    segmentation_file_uploaded = request.args.get("uploaded", "False").lower() == "true"

    # Render segmentation.html with the 2 forms
    return render_template(
        "segmentation.html",
        file_upload_form=file_upload_form,
        segmentation_parameters_form=segmentation_parameters_form,
        # Boolean that shows only one of the forms
        segmentation_file_uploaded=segmentation_file_uploaded,
    )


@segmentation_bp.route("/upload", methods=["POST"])
@login_required
def upload_segmentation_dataset_file():
    """Validates the file-uploading form and saves it after preprocessing."""

    file_upload_form = FileUploadForm()
    segmentation_parameters_form = SegmentationParametersForm()

    if file_upload_form.validate_on_submit():
        print("FORM VALIDATION PASSED")
        try:
            # Retrieve the file
            file = file_upload_form.file.data

            is_valid_file, validation_message = DatasetFileService.validate_datasetfile(
                file
            )

            # Validate and save the file
            if is_valid_file:
                file_is_saved, dataset_file_id = DatasetFileService.save_datasetfile(
                    file, "segmentation"
                )
                session["segmentation_file_uploaded"] = file_is_saved
                session["dataset_file_id"] = dataset_file_id

            else:
                flash(
                    validation_message,
                    "error",
                )
            return redirect(
                url_for(
                    "segm.segmentation_dashboard",
                    uploaded=session.get("segmentation_file_uploaded"),
                )
            )

        except RequestEntityTooLarge:
            flash("The file is too large. Please upload a smaller file.", "error")

    else:
        print("FORM VAL FAILED", file_upload_form.file.errors)
        return render_template(
            "segmentation.html",
            file_upload_form=file_upload_form,  # This still contains the errors
            segmentation_parameters_form=segmentation_parameters_form,
            segmentation_file_uploaded=False,
        )


@segmentation_bp.route("/change_file", methods=["POST"])
@login_required
def change_segmentation_dataset_file():
    """Redirects user back to the file-uploading form."""
    session["segmentation_file_uploaded"] = False
    return redirect(
        url_for(
            "segm.segmentation_dashboard",
            uploaded=session.get("segmentation_file_uploaded"),
        )
    )


@segmentation_bp.route("/cluster_customers", methods=["POST"])
@login_required
def cluster_customers():
    """Takes input from Segmentation Parameters form and returns cluster counts after segmentation."""

    # Form to input number of clusters and clustering metric
    form = SegmentationParametersForm()

    if form.validate_on_submit():
        print("segm form passedd")

        # Get the dataset inside the submitted file
        df = DatasetFileService.get_session_dataframe()

        # Retrieve number of clusters and clustering metric from the form
        num_of_clusters = form.number_choice.data
        chosen_metric = form.metric.data
        session["chosen_metric"] = (
            chosen_metric  # Set the chosen metric into the session
        )

        # Cluster the dataset and set cluster counts in the session
        cluster_counts, metric_averages = SegmentationService.segment_customers(
            df, num_of_clusters, chosen_metric
        )
        if cluster_counts is None or metric_averages is None:
            return jsonify(
                {"success": False, "message": "Insufficient variation in data."}
            )

        session["cluster_counts"] = cluster_counts
        session["metric_averages"] = metric_averages
        print(cluster_counts)
        print(metric_averages)
        return jsonify({"success": True})
    else:
        print("segm form not passedd", form.errors)
        return jsonify({"success": False}), 400


@segmentation_bp.route("/get_cluster_profiles", methods=["GET"])
@login_required
def get_cluster_profiles():
    """Returns the chosen metric, cluster counts, and metric averages stored in the session."""

    # Get the chosen metric, cluster counts, and metric averages from the session
    chosen_metric = session.get("chosen_metric", "Metric not chosen")
    cluster_counts = session.get("cluster_counts", {})
    metric_averages = session.get("metric_averages", {})

    total_customers = sum(cluster_counts.values())
    cluster_percentages = {
        cluster: (count / total_customers * 100) if total_customers > 0 else 0
        for cluster, count in cluster_counts.items()
    }
    return jsonify(
        {
            "cluster_counts": cluster_counts,
            "metric_averages": metric_averages,
            "cluster_percentages": cluster_percentages,
            "chosen_metric": chosen_metric,
        }
    )


@segmentation_bp.route("save_to_db", methods=["POST"])
@login_required
def save_segmentation_to_db():
    # Get the dataset file ID, chosen metric, cluster counts, and metric averages
    dataset_file_id = session.get("dataset_file_id")
    chosen_metric = session.get("chosen_metric", "Metric not chosen")
    cluster_counts = session.get("cluster_counts", {})
    metric_averages = session.get("metric_averages", {})

    try:
        # Save the data to the database
        SegmentationService.save_to_db(
            dataset_file_id, chosen_metric, cluster_counts, metric_averages
        )

        # Return a success response
        print("Segmentation report saved successfully!")
        return jsonify({"message": "Segmentation report saved successfully!"}), 200

    except Exception as e:
        print("Error:", e)
        return jsonify({"Error": str(e)}), 500

app/blueprints/segmentation/templates/macros/file_upload_macro.html
{% macro file_upload(form) %}
<!-- Form for file upload -->
<p
    class="mb-6 text-lg font-normal text-center text-white lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"
>
    Get started by uploading your customer sales dataset below.
</p>
<form
    method="post"
    action="{{ url_for('segm.upload_dataset_file') }}"
    class="flex flex-col items-center justify-center w-full"
    enctype="multipart/form-data"
>
    {{ form.hidden_tag() }}
    <!-- CSRF protection -->

    <div class="flex flex-col justify-center w-full max-w-sm">
        <label
            class="block mb-2 text-sm font-medium text-white dark:text-white"
            for="file_input"
        >
            {{form.file.label}}
        </label>

        <!-- File upload field -->
        {{ form.file(class="block w-full text-sm text-black border
        border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400
        focus:ring-2 focus:outline-none focus:ring-fyp-primary-100
        dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400") }}

        <!-- Form error messages -->
        {% if form.file.errors %}
        <div
            class="p-4 mt-2 text-sm text-center text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert"
        >
            <!-- Display each message -->
            {% for error in form.file.errors %}
            <span class="font-medium">{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}

        <!-- Other error messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Check if there are messages -->
        {% if messages %}
        <div
            class="p-4 mt-2 text-sm text-center text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert"
        >
            <!-- Display each message -->
            {% for category, message in messages %}
            <span class="font-medium">{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %} {% endwith %}

        <p
            class="mt-1 text-sm text-white dark:text-gray-300"
            id="file_input_help"
        >
            CSV, XLSX, XLS, or JSON only
        </p>
    </div>

    <!-- Submit button -->
    <div class="mt-4">
        {{ form.submit(class="text-white bg-fyp-tertiary-100
        hover:bg-fyp-tertiary-200 focus:ring-2 focus:outline-none
        focus:ring-fyp-primary-100 font-medium rounded-md text-sm px-5 py-2.5
        text-center") }}
    </div>
</form>
{% endmacro %}

app/blueprints/segmentation/templates/macros/segmentation_file_upload_macro.html
{% macro file_upload(form) %}
<!-- Form for file upload -->
<p
    class="mb-6 text-lg font-normal text-center text-white lg:text-xl sm:px-16 xl:px-48"
>
    Get started by uploading your customer sales dataset below.
    <br />
    <span class="text-sm text-fyp-tertiary-100">
        Make sure you include these columns:
        <br />
        Product ID, Customer ID, Order Date, Price, Quantity, Sales
    </span>
</p>
<form
    method="post"
    action="{{ url_for('segm.upload_segmentation_dataset_file') }}"
    class="flex flex-col items-center justify-center w-full"
    enctype="multipart/form-data"
>
    {{ form.hidden_tag() }}
    <!-- CSRF protection -->

    <div class="flex flex-col justify-center w-full max-w-sm">
        <label
            class="block mb-2 text-sm font-medium text-white dark:text-white"
            for="file_input"
        >
            {{form.file.label}}
        </label>

        <!-- File upload field -->
        {{ form.file(class="block w-full text-sm text-black border rounded-lg
        file:rounded-l-lg cursor-pointer bg-white focus:ring-2
        focus:outline-none focus:ring-fyp-primary-100 h-10 file:h-10
        file:bg-fyp-primary-100 file:text-white file:font-medium file:px-4
        file:hover:bg-fyp-secondary-100") }}

        <!-- Form error messages -->
        {% if form.file.errors %}
        <ul
            class="p-4 mt-2 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert"
        >
            {% for error in form.file.errors %}
            <li class="font-medium">{{error}}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <!-- Other error messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Check if there are messages -->
        {% if messages %}
        <div
            class="p-4 mt-2 text-sm text-center text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert"
        >
            <!-- Display each message -->
            {% for category, message in messages %}
            <span class="font-medium">{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %} {% endwith %}

        <p
            class="mt-1 text-sm text-white dark:text-gray-300"
            id="file_input_help"
        >
            CSV or XLSX only
        </p>
    </div>

    <!-- Submit button -->
    <div class="mt-4">
        {{ form.submit(class="text-white bg-fyp-tertiary-100
        hover:bg-fyp-tertiary-200 focus:ring-2 focus:outline-none
        focus:ring-fyp-primary-100 font-medium rounded-md text-sm px-5 py-2.5
        text-center") }}
    </div>
</form>
{% endmacro %}

app/blueprints/segmentation/templates/macros/segmentation_view_macro.html
{% macro segmentation_view(form) %}
<div class="w-full border-white flex items-center justify-between">
    <div class="w-full border-white flex flex-col justify-center items-center">
        <!-- Segmentation parameters form -->
        {% from
        "macros/segmentation_view_submacros/segmentation_parameters_form_macro.html"
        import segmentation_parameters_form %}
        {{segmentation_parameters_form(form=form)}}

        <!-- Change file button -->
        <form
            class="mt-4 border-white"
            method="post"
            action="{{ url_for('segm.change_segmentation_dataset_file') }}"
        >
            <button
                type="submit"
                class="text-white bg-fyp-tertiary-100 hover:bg-fyp-tertiary-200 focus:ring-2 focus:outline-none focus:ring-fyp-primary-100 font-medium rounded-md text-sm px-5 py-2.5 text-center"
            >
                Change file
            </button>
        </form>

        <!-- Error messages -->
        <!-- Other errors -->
        <div
            id="segmentation-parameters-form-errors"
            class="p-4 mt-4 text-sm text-center text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert"
        ></div>
    </div>

    <div class="border-white w-full flex flex-col justify-center items-center">
        <!-- Segmentation output chart -->
        {% from
        "macros/segmentation_view_submacros/segmentation_chart_macro.html"
        import segmentation_chart %} {{segmentation_chart()}}
    </div>
</div>
{% endmacro %}

app/blueprints/segmentation/templates/macros/segmentation_view_submacros/segmentation_chart_macro.html
{% macro segmentation_chart() %}
<div
    class="w-full h-auto flex flex-col items-center px-4 mx-auto border-x border-white text-white"
>
    <canvas
        id="cluster-chart"
        width="auto"
        height="auto"
        class="border-b border-white"
    ></canvas>
    <!-- Download report button -->
    <form class="mt-4 border-white">
        <button
            id="download-segmentation-report-button"
            type="submit"
            class="text-white bg-fyp-tertiary-100 hover:bg-fyp-tertiary-200 focus:ring-2 focus:outline-none focus:ring-fyp-primary-100 font-medium rounded-md text-sm px-5 py-2.5 text-center"
            style="display: none"
        >
            Download Report
        </button>
    </form>
    <!-- Processing message -->
    <p
        id="segmentation-message"
        class="border-white mt-4 text-fyp-tertiary-100 font-bold text-sm"
        style="display: none"
    >
        Segmenting customers, please wait...
    </p>
</div>
<script src="{{ url_for('segm.static', filename='js/segmentation_chart.js') }}"></script>

{% endmacro %}

app/blueprints/segmentation/templates/macros/segmentation_view_submacros/segmentation_parameters_form_macro.html
{% macro segmentation_parameters_form(form) %}
<form
    id="segmentation-parameters-form"
    class="border-b border-white flex flex-col items-center justify-center mx-4 py-5 px-8"
>
    {{ form.hidden_tag() }}
    <!-- CSRF protection -->

    <div class="border-white flex flex-col justify-center w-full max-w-sm">
        <!-- Dropdown to select segmentation metric -->
        <fieldset class="border-white flex flex-col">
            <label class="text-sm font-medium text-white" for="metric">
                {{ form.metric.label }}
            </label>
            {{ form.metric( id="metric", class="text-black bg-white
            hover:bg-gray-100 focus:ring-2 focus:outline-none
            focus:ring-fyp-primary-100 font-medium rounded-lg text-sm px-5
            py-2.5 mt-2 text-center", required=True ) }}
        </fieldset>

        <!-- Number of clusters to form -->
        <fieldset class="border-white mt-6 flex flex-col">
            <!-- Radio button for number of clusters (auto/custom) -->
            <label class="text-sm font-medium text-white">
                {{ form.number_choice.label }}
            </label>
            <div class="grid grid-cols-5 gap-1 mt-2">
                {% for subfield in form.number_choice %}
                <div class="flex items-center">
                    {{ subfield( class="w-4 h-4 border-gray-300 focus:ring-2
                    focus:ring-fyp-primary-100 ", ) }}
                    <label class="ms-2 me-4 text-sm font-medium text-white">
                        {{ subfield.label.text }}
                    </label>
                </div>
                {% endfor %}
            </div>

            <!-- Note message -->
            <p
                class="border-white mt-4 text-fyp-tertiary-100 font-bold text-sm"
            >
                NOTE: The chart may show lesser clusters than selected. This is
                because the selected number exceeds the number of distinct
                clusters in the data and is therefore impossible.
            </p>
        </fieldset>

        <!-- Other error messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Check if there are messages -->
        {% if messages %}
        <div
            class="p-4 mt-2 text-sm text-center text-red-800 rounded-lg bg-red-50"
            role="alert"
        >
            <!-- Display each message -->
            {% for category, message in messages %}
            <span class="font-medium">{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %} {% endwith %}
    </div>

    <!-- Submit button -->
    {{ form.submit(class="text-white bg-fyp-tertiary-100
    hover:bg-fyp-tertiary-200 focus:ring-2 focus:outline-none
    focus:ring-fyp-primary-100 font-medium rounded-md text-sm mt-4 px-5 py-2.5
    text-center") }}
</form>

{% endmacro %}

app/blueprints/segmentation/templates/macros/segmentation_view_submacros/spinner_icon_macro.html
{% macro spinner_icon() %}

<div id="segmentation-chart-loader-icon" role="status" class="hidden">
    <div
        class="inline-block w-8 h-8 border-4 border-t-4 border-gray-200 rounded-full animate-spin dark:border-gray-600"
    ></div>
    <span class="sr-only">Loading...</span>
</div>

{% endmacro %}

app/blueprints/segmentation/templates/segmentation.html
{% extends "baselayout.html" %}
<!-- Page title -->
{% block title %}Segment Customers - OptiPrice{% endblock %} {% block content %}

<!-- Page content -->
<!-- Page header -->
<h1
    class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-center text-white md:text-5xl lg:text-6xl dark:text-white"
>
    Segment your
    <span class="text-fyp-tertiary-100">Customers</span>
</h1>
<div
    class="w-full border border-fyp-secondary-100 flex flex-col justify-center items-center bg-fyp-secondary-100 hover:border-fyp-tertiary-100 transition-all duration-100 ease-in-out p-8 m-4"
>
    <!-- File upload input field -->
    <!-- If file not uploaded, show upload form -->
    {% if not segmentation_file_uploaded %} {% from
    "macros/segmentation_file_upload_macro.html" import file_upload %}
    {{file_upload(form=file_upload_form)}}

    <!-- Else show segmentation view macro -->
    {% else %} {% from "macros/segmentation_view_macro.html" import
    segmentation_view %}
    {{segmentation_view(form=segmentation_parameters_form)}} {% endif %}
</div>

{% endblock %}

app/blueprints/segmentation/templates/segmentation_parameters_macro.html
{% macro segmentation_parameters(form) %}
<form
    method="post"
    action="{{ url_for('segm.cluster_customers') }}"
    class="border-b border-white flex flex-col items-center justify-center mx-4 py-5 px-8"
    enctype="multipart/form-data"
>
    {{ form.hidden_tag() }}
    <!-- CSRF protection -->

    <div class="border-white flex flex-col justify-center w-full max-w-sm">
        <!-- Dropdown to select segmentation metric -->
        <fieldset class="border-white flex flex-col">
            <label
                class="text-sm font-medium text-white dark:text-white"
                for="metric"
            >
                {{ form.metric.label }}
            </label>
            {{ form.metric( id="metric", class="text-black bg-fyp-primary-100
            hover:bg-gray-300 focus:ring-4 focus:outline-none
            focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mt-2
            text-center dark:bg-blue-600 dark:hover:bg-blue-700
            dark:focus:ring-blue-800", required=True ) }}
        </fieldset>

        <!-- Number of clusters to form -->
        <fieldset class="border-white mt-6 flex flex-col">
            <!-- Radio button for number of clusters (auto/custom) -->
            <label class="text-sm font-medium text-white dark:text-white">
                {{ form.number_choice.label }}
            </label>
            <div class="grid grid-cols-5 gap-1 mt-2">
                {% for subfield in form.number_choice %}
                <div class="flex items-center">
                    {{ subfield( class="w-4 h-4 border-gray-300 focus:ring-2
                    focus:ring-blue-300 dark:focus:ring-blue-600
                    dark:focus:bg-blue-600 dark:bg-gray-700
                    dark:border-gray-600", ) }}
                    <label
                        class="ms-2 me-4 text-sm font-medium text-white dark:text-gray-300"
                    >
                        {{ subfield.label.text }}
                    </label>
                </div>
                {% endfor %}
            </div>
        </fieldset>

        <!-- Other error messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Check if there are messages -->
        {% if messages %}
        <div
            class="p-4 mt-2 text-sm text-center text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
            role="alert"
        >
            <!-- Display each message -->
            {% for category, message in messages %}
            <span class="font-medium">{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %} {% endwith %}
    </div>

    <!-- Submit button -->
    {{ form.submit(class="text-white bg-fyp-tertiary-100
    hover:bg-fyp-tertiary-200 focus:ring-4 focus:outline-none
    focus:ring-fyp-tertiary-100 font-medium rounded-md text-sm mt-8 px-5 py-2.5
    text-center") }}
</form>

{% endmacro %}

app/blueprints/segmentation/templates/segmentation_view_macro.html
{% macro segmentation_view(segmentation_parameters_form) %}
<div class="w-full border-white flex items-center justify-between">
    <div class="w-full border-white flex flex-col justify-center items-center">
        <!-- Segmentation parameters form -->
        {% from "segmentation_parameters_macro.html" import
        segmentation_parameters %}
        {{segmentation_parameters(form=segmentation_parameters_form)}}

        <!-- Change file button -->
        <div class="mt-4">
            <form
                method="post"
                action="{{ url_for('segm.change_dataset_file') }}"
            >
                <button
                    type="submit"
                    class="text-white bg-fyp-tertiary-100 hover:bg-fyp-tertiary-200 focus:ring-4 focus:outline-none focus:ring-white font-medium rounded-md text-sm px-5 py-2.5 text-center"
                >
                    Change file
                </button>
            </form>
        </div>
    </div>
    <!-- Segmentation output chart -->
    <div class="border-white w-full flex justify-center items-center">
        {% from "segmentation_chart_macro.html" import segmentation_chart %}
        {{segmentation_chart()}}
    </div>
</div>
{% endmacro %}